version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: 'bun'
    pull-request-branch-name:
      separator: '-'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      storybook:
        patterns:
          - 'storybook'
          - '@storybook/*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      vite:
        patterns:
          - 'vite'
          - 'vitest'

  - package-ecosystem: 'github-actions'
    pull-request-branch-name:
      separator: '-'
    directory: '/.github/workflows'
    schedule:
      interval: 'weekly'
