import {
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  BellOff,
  Bookmark,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleHelp,
  Clock,
  CodeXml,
  Copy,
  Download,
  Edit,
  ExternalLink,
  Eye,
  EyeClosed,
  EyeOff,
  File,
  FileText,
  Filter,
  Folder,
  HandHeart,
  Heart,
  HeartHandshake,
  Home,
  Image,
  Info,
  Link,
  Loader,
  Lock,
  LogOut,
  Mail,
  Menu,
  MessageCircle,
  MessageCircleMore,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Pause,
  Play,
  Plus,
  RefreshCw,
  Search,
  Send,
  Settings,
  Share,
  Star,
  Sun,
  ThumbsUp,
  Trash,
  Upload,
  User,
  Users,
  Video,
  X,
  ZoomIn,
  ZoomOut,
} from "lucide-react";
import type { ComponentProps, FunctionComponent, SVGProps } from "react";
import LinkedIn from "../assets/LinkedIn.svg?react";

/**
 * 외부 SVG 파일을 아이콘으로 변환하는 헬퍼 함수
 * - SVG를 React 컴포넌트로 import한 경우 이 함수로 감싸서 사용합니다
 * - fill="currentColor"를 자동으로 추가하여 색상 상속을 가능하게 합니다
 */
function convertSvgToIcon(Icon: FunctionComponent<SVGProps<SVGSVGElement>>) {
  return (args: ComponentProps<typeof Icon>) => (
    <Icon {...args} fill="currentColor" />
  );
}

export const icons = {
  alignCenter: AlignCenter,
  alignJustify: AlignJustify,
  alignLeft: AlignLeft,
  alignRight: AlignRight,
  archive: Archive,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  bell: Bell,
  bellOff: BellOff,
  bookmark: Bookmark,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  circleAlert: CircleAlert,
  circleHelp: CircleHelp,
  clock: Clock,
  codeXml: CodeXml,
  copy: Copy,
  download: Download,
  edit: Edit,
  externalLink: ExternalLink,
  eye: Eye,
  eyeClosed: EyeClosed,
  eyeOff: EyeOff,
  file: File,
  fileText: FileText,
  filter: Filter,
  folder: Folder,
  handHeart: HandHeart,
  heart: Heart,
  heartHandshake: HeartHandshake,
  home: Home,
  image: Image,
  info: Info,
  link: Link,
  loader: Loader,
  lock: Lock,
  logOut: LogOut,
  mail: Mail,
  menu: Menu,
  messageCircle: MessageCircle,
  messageCircleMore: MessageCircleMore,
  moon: Moon,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  pause: Pause,
  play: Play,
  plus: Plus,
  refreshCw: RefreshCw,
  search: Search,
  send: Send,
  settings: Settings,
  share: Share,
  star: Star,
  sun: Sun,
  thumbsUp: ThumbsUp,
  trash: Trash,
  upload: Upload,
  user: User,
  users: Users,
  video: Video,
  x: X,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  LinkedIn: convertSvgToIcon(LinkedIn),
};

export type IconName = keyof typeof icons;
